store_backend_homepage:
    path:     /hello/{name}
    defaults: { _controller: storeBackendBundle:Default:index }

# nom de la route
store_backend_index:
    path: /dashboard #chemin / URI de la route
    defaults: { _controller: storeBackendBundle:Main:index } # le controleur et l'action appelé // "Main" => nom du controleur

#Pages statics
store_backend_statics:
    resource: "@storeBackendBundle/Resources/config/statics.yml"
    prefix:   /

#Pages products
store_backend_products:
    resource: "@storeBackendBundle/Resources/config/modules/product.yml"
    prefix:   /products

#Pages category
store_backend_categories:
    resource: "@storeBackendBundle/Resources/config/modules/category.yml"
    prefix: /categories

#Pages cms
store_backend_cms:
    resource: "@storeBackendBundle/Resources/config/modules/cms.yml"
    #Ajouter mon argument {_locale} pour traduire tout mon module cms
    #au niveau du routing
    #{_locale}:Argument spéciale au routing reconnus par le systeme d'internationalisation de Symfony
    prefix: /{_locale}/cms
    requirements:
        _locale: en|fr|es

#Pages supplier
store_backend_suppliers:
    resource: "@storeBackendBundle/Resources/config/modules/supplier.yml"
    prefix: /suppliers

store_backend_sliders:
    resource: "@storeBackendBundle/Resources/config/modules/slider.yml"
    prefix: /sliders

store_backend_jewelers:
    resource: "@storeBackendBundle/Resources/config/modules/jeweler.yml"
    prefix: /jewelers