# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  store.backend.twig.store_backend_extension:
  #Notre classe qui va étendre Twig
          class: store\BackendBundle\Twig\Extensions\StoreBackendExtension
          tags:
              - { name: twig.extension }

  store.backend.listener.authentification: # Nom du services
          #Nom de ma classe avec namespaces
          class: store\BackendBundle\Listener\AuthentificationListener

          #Nom des services injecté en constructeur de ma classe
          arguments: ["@doctrine.orm.entity_manager", "@security.context"]

          #Etende le mécanisme de sécurity au niveau de l'interaction login
          #avec un mécanisme d'écouteur
          tags:
              - { name: kernel.event_listener, event: security.interactive_login, method: onAuthentificationSuccess }

  #Nom du bundle et nom de la classe
  store.backend.email: #Nom du service
              class: store\BackendBundle\Email\Email #classe service
              arguments: ["@mailer", "@twig"] #service Swift Mailer et du service Twig

  #Nom du service
  store.backend.notification:
            #classe avec namespace
              class: store\BackendBundle\Notification\Notification
              arguments: ["@session"]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
