#Page list of category
store_backend_category_list:
    path:     /list
    defaults: { _controller: storeBackendBundle:Category:list } #NomduBundle:NomduControlleur:Nomdel'Action

#Page view a category
store_backend_category_view:
    path:     /view/{id}/{name}
    defaults: { _controller: storeBackendBundle:Category:view } #NomduBundle:NomduControlleur:Nomdel'Action
    requirements:
      id: \d+
      _method: GET

store_backend_category_remove:
    path:     /remove/{id}
    defaults: { _controller: storeBackendBundle:Category:remove }

store_backend_category_new:
    path:     /new
    defaults: { _controller: storeBackendBundle:Category:new }