#Page list of cms
store_backend_cms_list:
    path:     /list
    defaults: { _controller: storeBackendBundle:CMS:list } #NomduBundle:NomduControlleur:Nomdel'Action

#Page view a cms
store_backend_cms_view:
    path:     /view/{id}/{name}
    defaults: { _controller: storeBackendBundle:CMS:view } #NomduBundle:NomduControlleur:Nomdel'Action
    requirements:
      id: \d+
      name: "[a-zA-Z0-9-]{3,30}"
      _method: GET
