#Page list of cms
store_backend_cms_list:
    path:     /list
    defaults: { _controller: storeBackendBundle:CMS:list } #NomduBundle:NomduControlleur:Nomdel'Action

#Page view a cms
store_backend_cms_view:
    path:     /view/{id}/{name}
    defaults: { _controller: storeBackendBundle:CMS:view } #NomduBundle:NomduControlleur:Nomdel'Action
    requirements:
      id: \d+
      _method: GET

store_backend_cms_remove:
    path:     /remove/{id}
    defaults: { _controller: storeBackendBundle:CMS:remove }

store_backend_cms_new:
    path:     /new
    defaults: { _controller: storeBackendBundle:CMS:new }

store_backend_cms_edit:
    path:     /edit/{id}
    defaults: { _controller: storeBackendBundle:CMS:edit }