#Page list of product
store_backend_product_list:
    path:     /list
    defaults: { _controller: storeBackendBundle:Product:list } #NomduBundle:NomduControlleur:Nomdel'Action#Page list of product

#Page view a product
store_backend_product_view:
    path:     /view/{id}/{name}
    defaults: { _controller: storeBackendBundle:Product:view } #NomduBundle:NomduControlleur:Nomdel'Action
    requirements:
      id: \d+
      name: .+
      _method: GET

#Remove a Product
store_backend_product_remove:
    path:     /remove/{id}
    defaults: { _controller: storeBackendBundle:Product:remove }


store_backend_product_new:
    path:     /new
    defaults: { _controller: storeBackendBundle:Product:new }

store_backend_product_edit:
    path:     /edit/{id}
    defaults: { _controller: storeBackendBundle:Product:edit }

store_backend_product_activate:
    path:     /activate/{id}/{action}
    defaults: { _controller: storeBackendBundle:Product:activate }

store_backend_product_cover:
    path:     /cover/{id}/{action}
    defaults: { _controller: storeBackendBundle:Product:cover }
