store_backend_slider_list:
    path:     /list
    defaults: { _controller: storeBackendBundle:Slider:list } #NomduBundle:NomduControlleur:Nomdel'Action#Page list of product

#Remove a Product
store_backend_slider_remove:
    path:     /remove/{id}
    defaults: { _controller: storeBackendBundle:Slider:remove }


store_backend_slider_new:
    path:     /new
    defaults: { _controller: storeBackendBundle:Slider:new }

store_backend_slider_edit:
    path:     /edit/{id}
    defaults: { _controller: storeBackendBundle:Slider:edit }
