#Page list of supplier
store_backend_supplier_list:
    path:     /list
    defaults: { _controller: storeBackendBundle:Supplier:list } #NomduBundle:NomduControlleur:Nomdel'Action

#Page view a supplier
store_backend_supplier_view:
    path:     /view/{id}/{name}
    defaults: { _controller: storeBackendBundle:Supplier:view } #NomduBundle:NomduControlleur:Nomdel'Action
    requirements:
      id: \d+
      _method: GET

store_backend_supplier_remove:
    path:     /remove/{id}
    defaults: { _controller: storeBackendBundle:Supplier:remove }
